### ISSUE TITLE
EFI

### ISSUE THREAD

**Issue by wenshuaihuy** [DreamSaddle/Lenovo-rescuer-R720-15IKBN-Hackintosh-EFI#1]
hello，用了您的EFI很棒，能安装了，但是安装的时候是繁体字这个是在config文件中设置的吗

**Comment by DreamSaddle** [comment]
你好。不太建议你使用这个了，这个是10.15的EFI。你可以使用[这个](https://github.com/happylzyy/Hackintosh-Lenovo-R720)，支持最新的montery版本。
注意安装后出现核显驱动失败查看下issues。

**Comment by wenshuaihuy** [comment]
好的 谢谢啦
